version: "3.8"
services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      SERVICES: 1
      TASKS: 1
      NETWORKS: 1
      SWARM: 1
      EVENTS: 1
      VERSION: 1
    restart: always
    networks:
      - internal

  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: unless-stopped
    ports:
      - "${HTTP_IP_ADDRESS}:${HTTP_PORT}:80"
      - "${HTTP_IP_ADDRESS}:${HTTPS_PORT}:443"
      - "${SFTP_IP_ADDRESS}:${SFTP_PORT}:22"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      - ./traefik/traefik.yaml:/traefik.yaml:ro
      - ./traefik/letsencrypt:/letsencrypt
      - ./traefik/logs:/logs
      - ./certs:/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.options=mtls@file"
    networks:
      - internal
      - traefik_network
  sftp:
    image: atmoz/sftp
    container_name: sftp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.sftp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sftp.entrypoints=sftp"
      - "traefik.tcp.routers.sftp.service=sftp"
      - "traefik.tcp.services.sftp.loadbalancer.server.port=22"
    volumes:
      - ./sftp/keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./sftp/users.conf:/etc/sftp/users.conf:ro
    networks:
      - traefik_network
networks:
  internal: {}
  traefik_network:
    external: true
