tls:
  options:
    default:
      minVersion: VersionTLS12
    mtls:
      minVersion: VersionTLS12
      clientAuth:
        caFiles:
          - '/certs/ca.crt'
        clientAuthType: RequireAndVerifyClientCert
