DOMAIN=$1
NAME=$2
NETWORK=$3

MYSQL_PASSWORD=$(openssl rand -base64 12)
MYSQL_ROOT_PASSWORD=$(openssl rand -base64 12)

cat <<EOF
TEMPLATE=wordpress
INSTANCE_NAME="${NAME}"
INSTANCE_DOMAIN="${DOMAIN}"
INSTANCE_MYSQL_PASSWORD="${MYSQL_PASSWORD}"
INSTANCE_MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
DOCKER_NETWORK="${NETWORK}"
EOF
