DOMAIN=$1
NAME=$2
INSTANCE=$3

MYSQL_PASSWORD=$(openssl rand -base64 12)
MYSQL_ROOT_PASSWORD=$(openssl rand -base64 12)

cat <<EOF
TEMPLATE=wordpress
INSTANCE_NAME="${NAME}"
INSTANCE_DOMAIN="${DOMAIN}"
MYSQL_PASSWORD="${MYSQL_PASSWORD}"
MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
EOF
